### ISSUE TITLE
OpenBLAS v0.3.8

### ISSUE THREAD

**Issue by tylerjereddy** [MacPython/openblas-libs#16] opened 2020-02-10 22:31 UTC
This was released yesterday: https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.8

I'll proceed with stable release binary builds once the rackspace/hosting issue is sorted out. Perhaps could place the artifacts as GitHub release in the absence of an automation solution as Matti suggests, in the short term, as long as they can be pulled from some temporary CI location after the builds.

**Comment by tylerjereddy** [comment] 2020-02-21 21:51
Such a large number of issues have been discovered in `v0.3.8` that it seems `v0.3.9` will be released in ~2 weeks if possible, so we may target that once our asset storage/infrastructure is sorted out.

**Comment by mattip** [comment] 2020-02-24 08:18
I wonder what is causing the segfault on 32 bits in MacPython/numpy-wheels#73. It could be fixed in 0.3.8, or it could be caused by using libfortran.so.3 from an earlier libfortran with the manylinux2010 image. Of course it does not reproduce on my machine, but I think the Travis hardware has avx512f (due to the other issues we were seeing) while I only have avx2

**Closed** 2020-03-08 15:37 UTC
