### ISSUE TITLE
create release artifacts of this repo

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#14] opened 2020-02-09 20:56 UTC
This repo is a little different that the other MacPython wheel-producing ones. While the wheels may find a home on a PyPI-like index, the tarballs here (and perhaps the mingw ones?) I think will need a different solution. One relatively simple thing would be to create releases and host them here. Thoughts?

**Comment by tylerjereddy** [comment] 2020-02-10 20:13
I don't know much about GitHub releases so not sure I can comment on the drawbacks. Do we have a free extension with rackspace for a while now?

**Comment by mattip** [comment] 2020-02-10 20:16
Someone is doing the [releases on scipy/scipy](https://github.com/scipy/scipy/releases). Those artifacts are available via a URL like https://github.com/scipy/scipy/releases/download/v1.2.3/scipy-1.2.3-cp27-cp27mu-manylinux1_x86_64.whl which is pretty easy to parse

**Comment by tylerjereddy** [comment] 2020-02-10 20:17
Oh right, that's me. I thought you meant the new Workflows stuff

**Comment by ogrisel** [comment] 2020-02-12 12:46
Here are the docs to deploy release artifacts to github:

- for travis: https://docs.travis-ci.com/user/deployment/releases/
- for appveyor: https://www.appveyor.com/docs/deployment/github/

**Comment by ogrisel** [comment] 2020-02-16 22:42
For information, I discovered that it's possible to upload arbitrary files (that are neither wheels nor conda packages) to anaconda.org.

I started changing the CI scripts to upload anaconda artifacts for openblas-libs to anaconda.org (in the shared multibuild-wheels-staging organization):

https://github.com/ogrisel/openblas-libs/tree/anaconda-upload

I am waiting for appveyor to complete but if it works I will open a PR.

@matthew-brett you might be interested in the above as well.

**Comment by tylerjereddy** [comment] 2020-02-16 22:52
Sounds interesting. I've been working on the anaconda.org transition for scipy-wheels initially: https://github.com/MacPython/scipy-wheels/pull/68

What happens if/when we hit the 3GB free limit? For the forced replacements of wheels that may be less likely, but with a progressive accumulation of artifacts maybe it could happen, not sure.

**Comment by ogrisel** [comment] 2020-02-17 07:22
For nightly builds we should not hit the 3GB limit if we delete older wheels on a regular basis (we can do a cron job somewhere to do this).

For release staging, e.g. project can create its own organization on anaconda to get its own 2GB limit. The shared staging area is just a convenience for starting but it does not really need to be shared.

Also I was I contact with people at anaconda and they will probably raise our storage quota if we ask them as long as the bandwidth stays similar to way we had on rackspace.

**Comment by ogrisel** [comment] 2020-02-17 07:28
About release staging: nowadays it's possible to use a single CI config for the 3 main platforms (e.g. travis and azure pipelines can do Windows, macOS and Linux). On Azure Pipelines in particular it's possible to copy release artifacts to a shared folder visible to all the workers of the same build and have a dag structured dependency to collect all the wheels together and maybe publish them all at once to pypi.org if all the tests for all the platforms passed. See we would actually not need anaconda.org for release staging.


Also on Azure and Travis it's possible to use regular bash on windows for all the steps which makes it much simpler to share the same CI scripts for the 3 platforms.

**Comment by mattip** [comment] 2020-02-17 07:42
Your [branch](https://github.com/ogrisel/openblas-libs/commit/707c899b872101e987d47646ea207078fcc502f2) seems quite straightforward. I do wonder if releases here would not serve our purpose better though. What would the URL look like to download the openblas-lib for use in other projects?

**Comment by ogrisel** [comment] 2020-02-17 08:04
I updated the travis secret, added more comments on the token configuration and open #17.

The release would work as well here is a simulated URL:

https://github.com/MacPython/openblas-libs/releases/download/v0.3.5-605-gc815b8fb/openblas64_-v0.3.5-605-gc815b8fb-manylinux1_x86_64.tar.gz

On anaconda it looks like:

https://anaconda.org/multibuild-wheels-staging/openblas/v0.3.5-605-gc815b8fb/download/openblas64_-v0.3.5-605-gc815b8fb-manylinux1_x86_64.tar.gz

**Comment by charris** [comment] 2020-02-17 17:01
We (NumPy) want to control the wheel uploads to PyPI because we generate hashes for the released wheels.

**Comment by ogrisel** [comment] 2020-02-17 18:23
> We (NumPy) want to control the wheel uploads to PyPI because we generate hashes for the released wheels.

I am curious about more details about your release process. Are the hashes you mentions the same as those computed by PyPI?

https://pypi.org/project/numpy/#copy-hash-modal-f160f956-126a-4ccc-981d-c19883a3ae48

Do you keep an independent copy of the hash you generate before uploading to pypi to check that the binaries have not been corrupted after the release?

If your remark is about my suggested single-CI workflow [described above](https://github.com/MacPython/openblas-libs/issues/14#issuecomment-586852988) It should be possible to compute those hashes in the final stage of the Azure pipeline configuration and those hashes could be published to an independent append-only log (e.g. a dedicated twitter feed) and it would also be possible to have a scheduled jobs that would periodically download past released wheels, recompute their hashes and compare those to the values published on the append-only log.

**Comment by charris** [comment] 2020-02-17 18:42
We don't use the PyPI hashes, but rather publish our own in the release notes on Github. That said, I'm not convinced the hashes are actually useful. @rgommers Thoughts?

**Comment by tylerjereddy** [comment] 2020-02-17 18:49
I guess the idea is the release manager uses their own secure signing mechanism with a published public portion of their key, or something like that. Wouldn't be surprised if it could be streamlined with some careful thought I suppose. The README gets updated with the newly-downloaded file hashes after staging, but in theory I suppose you might be able to automate that.

**Comment by rgommers** [comment] 2020-02-17 19:33
I think the hashes are useful. We haven't needed them yet, luckily, but when there's any doubt about whether the PyPI wheels have been messed with or not, then having a pre-upload hash seems much better than relying on what PyPI itself tells us (cause how would you know that's not simply updated itself or has also been messed with?).

> If your remark is about my suggested single-CI workflow [described above](https://github.com/MacPython/openblas-libs/issues/14#issuecomment-586852988) It should be possible to compute those hashes in the final stage of the Azure pipeline configuration and those hashes could be published to an independent append-only log (e.g. a dedicated twitter feed) and it would also be possible to have a scheduled jobs that would periodically download past released wheels, recompute their hashes and compare those to the values published on the append-only log.

This seems like a nice extra security measure.

**Comment by ogrisel** [comment] 2020-02-19 09:44
@tylerjereddy thanks for merging:  #17. Most of the artifacts where uploaded successfully to:

https://anaconda.org/multibuild-wheels-staging/openblas-libs/files

However there are two problems:

1. the appveyor builds did not upload the artifacts to the anaconda container:

```
OPENBLAS_LIBS_STAGING_UPLOAD_TOKEN is not defined: skipping.
```
See end of the log:

https://ci.appveyor.com/project/matthew-brett/openblas-libs/builds/30898907/job/1uregccm5wbj8spp#L13201

I suspect that the problem is that the secret that I encrypted with my own appveyor account is not valid for the `MacPython/openblas-libs` repo. Can you please try to re-encrypt this token an update the following line in the appveyor config?

https://github.com/MacPython/openblas-libs/blob/master/appveyor.yml#L10-L16

You should be able to retrieve the value of the token by clicking on the "view" button at the bottom of this page:

https://anaconda.org/multibuild-wheels-staging/settings/access

![Screenshot from 2020-02-19 10-41-16](https://user-images.githubusercontent.com/89061/74821827-7cfab080-5304-11ea-8d9a-ca55428575ec.png)

2. the upload of the PPC artifact has failed on travis: https://travis-ci.org/MacPython/openblas-libs/jobs/652316316?utm_medium=notification&utm_source=github_status

**Comment by tylerjereddy** [comment] 2020-02-20 03:49
Looks like the second point is resolved now.

The first one is more annoying--I'll try to do that tomorrow. I wish Appveyor had the Travis-like interface where I could just copy/paste the key from Anaconda.org right in a secret variable slot in the UI.

**Comment by tylerjereddy** [comment] 2020-02-20 03:54
I think Matthew has the `Enable secure variables in Pull Requests from the same repository only` checked in the Appveyor settings (I can't access those). It remains unclear to me why that would affect your key once it was merged in though.

I guess trying to encrypt as a "collaborator" & then open a PR from a feature branch within the repo proper is at least worth a try.

**Comment by mattip** [comment] 2020-02-20 04:52
ping @matthew-brett

**Comment by ogrisel** [comment] 2020-02-20 10:16
> Enable secure variables in Pull Requests from the same repository only

This is better to leave this as this. Otherwise it would be easy for an attacker to open a PR to steal the token value.

> I guess trying to encrypt as a "collaborator" & then open a PR from a feature branch within the repo proper is at least worth a try.

+1

**Comment by ogrisel** [comment] 2020-02-20 13:13
@matthew-brett apparently I cannot encrypt the secret variable for `OPENBLAS_LIBS_STAGING_UPLOAD_TOKEN`. It has to be done with your account on:

https://ci.appveyor.com/tools/encrypt

by using the value of the token defined at the bottom of this page:

https://anaconda.org/multibuild-wheels-staging/settings/access

and then added there:

https://github.com/MacPython/openblas-libs/blob/master/appveyor.yml#L10-L16

**Comment by matthew-brett** [comment] 2020-02-20 15:43
Thanks - I gave it a shot -
https://github.com/MacPython/openblas-libs/commit/7296eac

**Comment by tylerjereddy** [comment] 2020-02-20 16:59
Hmm, even for Matthew's push I see `OPENBLAS_LIBS_STAGING_UPLOAD_TOKEN is not defined: skipping` in the Appveyor logs.

https://ci.appveyor.com/project/matthew-brett/openblas-libs/builds/30940670/job/w35qu69vm85j9tk0

**Comment by tylerjereddy** [comment] 2020-02-20 17:15
For completeness, I've open a PR from a feature branch within the repo using a token I encrypted while "logged in" to Appveyor: https://github.com/MacPython/openblas-libs/pull/19

Not optimistic though :)

**Comment by matthew-brett** [comment] 2020-02-20 17:43
It's possible I encrypted the wrong thing.   The thing I encrypted started with 5 and ended with a  . Does that look right?

**Comment by tylerjereddy** [comment] 2020-02-20 17:48
Hmm, doesn't look right, the token to encrypt should come from clicking on the "view" link from the anaconda.org page:

![image](https://user-images.githubusercontent.com/7903078/74963156-7c2e5100-53ce-11ea-8122-cdf2a7b0f047.png)

**Comment by tylerjereddy** [comment] 2020-02-20 17:51
On the other hand, that might be orthogonal, since I'd expect encrypting the wrong thing to fail at the upload stage, but not fail to define the variable in appveyor itself.

**Comment by matthew-brett** [comment] 2020-02-20 17:52
Well - I've tried encrypting what must be the right thing - starting with m ending with 7.

**Comment by tylerjereddy** [comment] 2020-02-20 17:53
thanks, sounds correct

**Comment by tylerjereddy** [comment] 2020-02-21 03:20
Neither of our attempts worked:

`bash --login %SCRIPT_DIR%upload_to_anaconda_staging.sh`

results in a failure to find the secret variable on Appveyor.

**Comment by tylerjereddy** [comment] 2020-02-21 03:33
It looks like we have sufficient permissions to enable, adjust or remove webhooks, so I suppose stronger actions like pointing to another service/instance of appveyor are perhaps possible if we really had to. Looks like Matthew was the original author of the appveyor config; not sure about the appveyor account associated with the project though.

**Comment by ogrisel** [comment] 2020-02-21 08:32
This is weird: 13e5a79 still leads to:

```
OPENBLAS_LIBS_STAGING_UPLOAD_TOKEN is not defined: skipping.
```

Full log: https://ci.appveyor.com/project/matthew-brett/openblas-libs/builds/30944304/job/e06xi9wrx7phhf3w .

**Comment by ogrisel** [comment] 2020-02-21 08:51
To speed up the debugging, you can push your experiments in this branch where I only kept the zip upload step and disabled compute-intensive build and test steps:

https://github.com/MacPython/openblas-libs/tree/debug-appveyor-upload

You can see that the following checks do not find the secret variable:

```
if "%OPENBLAS_LIBS_STAGING_UPLOAD_TOKEN%"=="" (echo "missing token") else (echo "token ok")
"missing token"
if "%OPENBLAS_LIBS_STAGING_UPLOAD_TOKEN%"=="" (echo "missing token") else (echo "token ok")
"missing token"
if "%OPENBLAS_LIBS_STAGING_UPLOAD_TOKEN%"=="" (echo "missing token") else (echo "token ok")
"missing token"
```

so the problem is not that the value is invalid, it's that the secret variable is not decoded at all...

**Comment by ogrisel** [comment] 2020-02-21 08:55
> It looks like we have sufficient permissions to enable, adjust or remove webhooks, so I suppose stronger actions like pointing to another service/instance of appveyor are perhaps possible if we really had to. Looks like Matthew was the original author of the appveyor config; not sure about the appveyor account associated with the project though.

+1 for trying to create a new dedicated appveyor account (aka organization) for openblas-libs. Do you want me to give it a try?

**Comment by matthew-brett** [comment] 2020-02-21 09:23
A new account / org seems like an excellent idea.  My account has got a 2.5 hour timeout, but a) you probably don't need that and b) you could ask for an upgrade for the new account too.

Is it possible that the variable name is too long?

**Comment by ogrisel** [comment] 2020-02-21 10:32
I don't think that's the case because I could make it work on my own personal account when working on the initial pull request, e.g.:

https://ci.appveyor.com/project/ogrisel/openblas-libs/builds/30840312/job/u2vxwcnqsy6f5blr

I will try to setup a new appveyor account.

**Comment by tylerjereddy** [comment] 2020-02-21 21:35
Thanks Olivier

**Comment by tylerjereddy** [comment] 2020-02-23 02:35
I may try the appveyor account think tomorrow myself if you don't beat me to it

**Comment by tylerjereddy** [comment] 2020-02-23 04:57
Ok, I've temporarily updated the settings for this repo to include a second webhook for my own appveyor instance/project. It seems the most recently-added webhook takes precedence as it is now using mine automatically in #19.

Fingers crossed that works since that PR is from a feature branch within the repo AND uses an encrypted value with the same account.

If it does not, I have not done anything irreversible---we could simply delete the new webhook and use the old one if we need to revert.

I'll check on it tomorrow morning.

**Comment by tylerjereddy** [comment] 2020-02-23 13:31
oof, still didn't work; maybe still a permissions thing unless you own the repo or something

**Comment by tylerjereddy** [comment] 2020-02-23 17:33
Maybe using Azure pipelines for those 3 Appveyor matrix entries is the next thing to think about. Azure allows the setting of secret variables to happen in the pipelines UI like Travis. As long as we have sufficient permission to try hooking up Azure.. maybe I'll try later today.

There's probably some migration cost/issues from Appveyor though. Pretty sure we do have some specific appveyor stuff, but maybe not a huge deal.

**Comment by charris** [comment] 2020-02-23 17:37
I'm all in favor of getting Azure pipelines building the windows wheels.

**Comment by tylerjereddy** [comment] 2020-02-24 01:37
I've updated #19 to use the encrypted variable from the appveyor settings UI itself, instead of pasting an encrypted value in the yml file. This should work with "collaborator" permissions, but only the CI result will tell.. so I'll check back in a few hours.

I didn't know this was possible b/c you have to "mouse over" to see the encryption option next to env variables.

The Azure thing seems to require higher permissions, so if I this works we may want to just go it with for at least a while.

**Comment by tylerjereddy** [comment] 2020-02-24 03:10
I'm observing the upload in appveyor in my new openblas-libs appveyor account, but my PR still pointed to Matthew's by default in the UI. I've temporarily removed the webhook for this and closed/reopened that PR.

It looks like the "pr" appveyor run will now point to my new appveyor account, so it should hopefully work. The "branch" appveyor run is still pointing to Matthew's appveyor, but that might just be b/c of the close/reopen not reflecting the webhook removal for a branch in the repo proper.

**Comment by tylerjereddy** [comment] 2020-02-24 16:57
All 14 OpenBLAS release artifacts are now visible at: https://anaconda.org/multibuild-wheels-staging/openblas-libs/files

The uploads were successful from the appveyor "pr" run in #19, so I've merged that.

So, I'll close this issue---let's open separate issues if we observe further problems in subsequent PRs.

**Closed by tylerjereddy** 2020-02-24 16:57 UTC

**Comment by tylerjereddy** [comment] 2020-02-25 02:08
They've bumped the account I put in to 90 minute timeout, hopefully that's enough for now: https://twitter.com/appveyor/status/1232115138443874304?s=20

**Comment by ogrisel** [comment] 2020-02-25 09:12
Thank you very much for @tylerjereddy and sorry from the lack of follow-up on my side. I was caught-up on other things for the past couple of days.
